INSERT INTO 
		autor (nome) 
VALUES
		('João Paulo Maida'),
		('Otávio Santana'),
		('Gilliard Cordeiro'),
		('Hugo Kotsubo'),
		('José Yoshiriro'),
		('Rafael Peixoto'),
		('Marcos Brizeno'),
		('Adolfo Eloy'),
		('Rodrigo Turini'),
		('Fernando Boaglio');
		
INSERT INTO
		livro (titulo, subTitulo, descricao, numeroPaginas, isbn, preco, dataLancamento, path) 
VALUES 
		('Teoria dos Grafos','Uma abordagem prática em Java',' Vivemos em um mundo conectado. Um simples tweet pode fazer com que empresas emerjam ou caiam em falência, ou uma pesquisa por um determinado item faz com que suas redes sociais sejam inundadas de anúncios oferecendo o menor preço. Como funcionam essas conexões? A Teoria dos Grafos é um ramo da matemática que está mais presente em nossas vidas do que pensamos. Aplicativos de GPS, inteligência artificial e redes sociais são exemplos de aplicações cotidianas dessa área, que conversa diretamente com programação e desenvolvimento de softwares.Neste livro, João Paulo Maida apresenta a Teoria dos Grafos, desde suas diversas aplicações, definições de conceitos como vértice, aresta, árvores, suas funções e características. Você vai aprender sobre métodos de buscas, análise de caminhos, construção e redução de árvores, conforme desenvolve na prática uma aplicação em Java para aplicar o que foi visto. Para isso, o livro aborda os algoritmos utilitários que respondem a questões do cotidiano: o de Dijkstra, Floyd-Warshall e Prim, tudo isso de forma descomplicada e leve.',203,'978-65-86110-51-7',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Teoria-dos-Grafos_large.webp?noAuth=true'),
		('Apache Cassandra','Escalabilidade horizontal para aplicações Java',' No concorrido mundo da tecnologia, melhorias de milissegundos em performance podem fazer toda a diferença para seus clientes. Dessa necessidade, surgiram diversos paradigmas e frameworks, exigindo paralelamente um bom e rápido desempenho na persistência da informação. Neste cenário nasceu o Apache Cassandra, o banco de dados NoSQL, elástico, tolerante a falhas e com um alto grau de performance. O Cassandra é um banco de dados não relacional originado pelo Facebook, e hoje é um projeto open source dentro da Apache Foundation com cases de sucessos nas maiores empresas do mundo, como o Netflix, GitHub, eBay, dentre outros.Neste livro, Otávio Santana aborda o Cassandra, seus conceitos e sua aplicabilidade com o Java. Após uma introdução aos bancos de dados não relacionais, você verá conceitos como a hierarquia, leitura e escrita, seu funcionamento no nó e sua orquestração dentro de um Cluster. Será apresentado o funcionamento prático da linguagem de comunicação Cassandra Query Language ou CQL, com dicas de modelagem e frameworks de mapeamento, dentre os quais o DataStax Mapper, Spring Data Cassandra, Hibernate OGM Cassandra e o Eclipse JNoSQL.',150,'978-65-86110-47-0',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Apache-Cassandra_large.webp?noAuth=true'),
		('Microsserviços e EJB',' Escale sua aplicação, não a complexidade',' Seja no modelo tradicional ou de microsserviços, separar nossa aplicação em partes menores facilita a escalabilidade, a manutenção, dentre outras qualidades que buscamos nos nossos projetos. Para desenvolver um bom back-end, não basta seguir uma receita pronta. É preciso realmente entender as ferramentas para tirar o máximo delas sem comprometer o desempenho. Em java, dentre as tecnologias para atingir esse objetivo, temos CDI, JPA e principalmente EJBs e JAX-RS.Neste livro, Gilliard Cordeiro ensina como escalar uma aplicação sem aumentar sua complexidade. Você verá como sair do básico, seja com microsserviços, seja em uma arquitetura mais tradicional. A primeira parte do livro é dedicada ao Thorntail, pensada principalmente em quem precisa rapidamente aprender como fazer um back-end, construindo uma API Rest com as tecnologias do Java EE (Jakarta EE). Já a segunda parte é focada em mostrar realmente como os EJBs funcionam por dentro. Ao fim do livro, você saberá como melhorar a performance de operações pesadas através de paralelismo, incluindo entre as técnicas a programação reativa.', 378,'978-65-86110-38-8',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Microservicos-EJB_large.webp?noAuth=true'),
		('Datas e horas','Conceitos fundamentais e as APIs do Java',' Toda aplicação precisa lidar com datas. Seja com os casos mais simples, como uma data de nascimento no cadastro de usuários, até os mais complexos, como um rastreamento completo de todos os eventos ocorridos com determinado produto, desde a sua confecção até a venda, com data e hora exatas em que cada etapa ocorreu. No desenvolvimento, é essencial ter um conhecimento maior sobre todos os conceitos envolvendo datas e horas. Sem saber como funcionam os fusos horários e demais detalhes, e como sua linguagem ou framework trabalha com eles, não é possível escrever um código confiável. Como eu sei que estou considerando este ou aquele fuso horário? Como meu código vai se comportar no exato momento em que ocorre a mudança para o horário de verão?Neste livro, Hugo Kotsubo trata essas e muitas outras questões envolvendo datas. Na primeira parte, você verá todos os conceitos importantes do ponto de vista do desenvolvimento de software. Por ser mais conceitual, essa parte não focará em nenhuma tecnologia ou linguagem específica, sendo interessante a todos os desenvolvedores. Em seguida, você se debruçará sobre as APIs da linguagem Java, começando com java.util.Date e java.util.Calendar, chegando por fim à API java.time, introduzida no Java 8, e que é muito superior à API antiga, em vários aspectos que serão explicados ao longo do livro.',375,'978-85-7254-005-6',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Datas-Horas-Java_large.webp?noAuth=true'),
		('Spock framework','Testes automatizados para Java, Android e REST','A presença de testes automatizados é importante para dar segurança em qualquer código. Seja para refatorá-lo, mantê-lo, seja para inserir novas funcionalidades, os testes permitem uma detecção mais rápida quando algum comportamento anterior é quebrado. Um software interage com diversos recursos dentro de seu ecossistema e provê diferentes tipos de interface para a execução de suas funcionalidades, e é necessário lidar com tudo isso ao criar seus testes automatizados. O Spock framework é uma ferramenta muito poderosa, que pode ser a grande aliada de sua equipe na construção mais rápida e simples de testes melhores e menos verbosos.Neste livro, José Yoshiriro ensina a utilizar as funcionalidades do Spock framework e apresenta as técnicas de teste, juntamente com exemplos didáticos e focados em problemas do mundo real para tecnologias que são padrão de mercado. Você conhecerá esta ferramenta completa, que dispensa a configuração de bibliotecas adicionais, e dominará suas principais funcionalidades: criação de simples testes unitários, uso de Mocks, o recurso de Data-Driven Testing, criação de testes unitários para Android, de integração para Spring e funcionais para REST APIs.',250,'978-85-94188-87-8',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Spock-Framework_large.webp?noAuth=true'),
		('Selenium WebDriver','Descomplicando testes automatizados com Java',' Testes de verificação e validação são considerados um elemento crítico para garantia da qualidade de software. O planejamento, execução e controle de teste são dispendiosos e trabalhosos no processo de desenvolvimento. Em vista disso, as atuais ferramentas de testes oferecem uma variedade de recursos que podem reduzir significativamente os problemas identificados, de modo a garantir a qualidade de software, aumentar a produtividade e diminuir os custos. Dentre elas, o Selenium WebDriver é uma excelente escolha para iniciarmos a automação dos nossos testes, pois é uma ferramenta livre, gratuita e permite o uso em diferentes linguagens de programação e browsers.Neste livro, Rafael apresenta de forma introdutória e objetiva como escrever testes automatizados para Web utilizando Selenium WebDriver e JUnit em Java. O autor demonstra passo a passo e com exemplos práticos como rodar testes automatizados em navegadores tanto convencionais, como sem interface gráfica. Você conhecerá os principais problemas e dificuldades de um projeto de automação e verá padrões de projeto, como Page Objects, que o ajudarão a escrever códigos mais limpos e de fácil manutenção. Ao final, você será capaz de configurar um ambiente e criar scripts de testes automatizados, bem como terá uma boa base para seguir para ferramentas e técnicas mais avançadas.',238,'978-85-94188-72-4',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Selenium-WebDriver_large.webp?noAuth=true'),
		('Refatorando com padrões de projeto','Um guia em Java',' Qualidade de código e refatoração são reconhecidamente assuntos que permanecem relevantes e pertinentes tanto para novos profissionais como para quem já sabe do que se trata: melhorar o design existente, aplicar mudanças em pequenos passos e evitar deixar o sistema quebrado. Ao aplicar refatorações, existem várias técnicas que podem ajudar a alcançar a melhoria desejada, de modo que o processo seja feito de maneira responsável e garantindo o funcionamento da aplicação por meio de testes unitários.Neste livro, Marcos Brizeno mostra como padrões de projeto podem servir como guias para a refatoração projetos Java, para que você saiba decidir quando ou não determinado padrão pode ser aplicado para alcançar o código ideal. Por meio de exemplos práticos, você terá um melhor entendimento sobre design orientado a objetos, permitindo identificar mais facilmente os problemas e implementar soluções flexíveis e fáceis de evoluir.',142,'978-85-94188-21-2',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Refatoracao-Java_large.webp?noAuth=true'),
		('OAuth 2.0','Proteja suas aplicações com o Spring Security OAuth2',' Quando se trata de proteger os recursos de uma aplicação, é comum utilizar OAuth. Ainda assim, percebe-se que ainda existe bastante confusão a respeito dele, havendo até cenários de brechas em sistemas grandes devido ao mau uso da tecnologia. OAuth 2.0 é um protocolo ou um framework? Será que deve ser usado para autenticação ou autorização?Neste livro, Adolfo Eloy vem desmistificar essas perguntas, em uma mescla de teoria e prática, alertando para a importância do uso seguro da tecnologia. Por meio de uma aplicação de exemplo, você aprenderá os principais componentes presentes no fluxo do OAuth 2.0, como Resource Owner, Client, Resource Server e Authorization Server, acompanhando diferentes cenários de utilização do protocolo, nos pontos cruciais de segurança da sua aplicação. ',366,'978-85-94188-12-0',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/OAuth-2.0_large.webp?noAuth=true'),
		('Java 9','Interativo, reativo e modularizado',' Com mais de 20 anos de plataforma, um novo Java surge com novidades importantes. O destaque especial vai para o sistema de módulos, o Jigsaw, e a modularização do próprio JDK. A linguagem também ficou interativa, com a adição de uma ferramenta de REPL (Read-Eval-Print Loop), e mais reativa, com uma API de fluxos inteiramente dedicada aos famosos Reactive Streams.As APIs de HTTP/2 Client, Logging e Stack-Walking são outros exemplos de novidades que serão explorados. Além disso, você verá surpresas como métodos privados em interfaces, arquivos de properties com suporte a UTF-8 e os vários novos métodos default nas APIs de Collection, Stream e outros.Neste livro, Rodrigo Turini mostrará as principais novidades do Java 9 com a criação de um projeto prático, no qual você acompanhará com as mãos na massa as mudanças da plataforma e como migrar os seus códigos para tirar proveito dos novos recursos.',273,'978-85-94188-09-0',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Java-9_large.webp?noAuth=true'),
		('Spring Boot','Acelere o desenvolvimento de microsserviços','  Spring Boot é uma maneira eficiente e eficaz de criar uma aplicação em Spring e facilmente colocá-la no ar, funcionando sem depender de um servidor de aplicação. Não se trata de um simples framework, mas de um conceito totalmente novo de criar aplicações web. Além de impulsionar o desenvolvimento para microsserviços, o Spring Boot ajuda na configuração importando e configurando automaticamente todas as dependências. Neste livro, Fernando Boaglio apresenta os principais componentes dessa arquitetura revolucionária. Você poderá tirar o máximo proveito dela vendo os exemplos de acesso a banco de dados, exibição de páginas web usando templates, serviços REST sendo consumidos por front-end em JQuery e AngularJS, testes unitários e de integração, deploy na nuvem e alta disponibilidade com Spring Cloud.',154,'978-85-94120-00-7',39.9,'2020-11-24','http://localhost:9444/s3/casadocodigojavaee/Spring_boot.webp?noAuth=true');


		

insert into 
		livro_autor (livros_id, autores_id) 
values 
		(1,1), 
		(2,2), 
		(3,3), 
		(4,4), 
		(5,5), 
		(6,6), 
		(7,7),
		(8,8),
		(9,9),
		(10,10);
		
insert into 
	systemuser (login,senha) 
values 
	('felipe@mandu.com', 'pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=');
	
insert into
	systemrole (name)
values
	('ADMIN');
	
insert into
	systemuser_systemrole
values
	(1, 'ADMIN');

 